Metrics/MethodLength:
  Enabled: false
AllCops:
  NewCops: enable
Style/MixinUsage:
  Enabled: false
Naming/ClassAndModuleCamelCase:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
